### ISSUE TITLE
One suggestion

### ISSUE THREAD

**Issue by eclectic-coding** [evilmartians/rubocoping-generator#1]
First of all, I have used your articles suggestions for about a year, and absolutely love the setup. I have incorporated them into my default Rails Template. Making a generator is a great idea. I gave it a test run today and have only one observation:

The generator asks a series of potentially six questions. The last question, is the only one that offers helpful text to the user of the expected input: `"Would you like to run RuboCop to check your configuration? (y/n)"`

If might be helpful to add `(y/n)` to the remain user input question prompts.

I will be glad to submit this short PR, but if not, thanks again for a great product and suggestions.

Chuck

**Comment by palkan** [comment]
Thanks for the suggestion! Added.
